## [Addon] DiscordChatのコンフィグです
## プレイヤーロールチェッカーのv4.21での動作確認をしています
## 欲しい機能などがあったらGitHubまたはKouta1212#0001にフレンドを送ってください
global-settings:
  ## [Feature] コンソールのログを取得するか
  console-log: true
  ## [Performance] プレイヤーロールチェッカーのプレイヤーデータをキャッシュするか
  cache-playerdata: true
  ## [Performance] ディスコードにチャットをしたときにプレイヤーデータを取得するか
  get-playerdata: false
  ## SkinUrl
  ## スキンを生成する方法
  ##- LINK 誰かのHTTPに依存してDiscordを見たプレイヤーに処理してもらいます！
  ##- LOCAL ローカルで生成します (HTTPリクエストが必要になります！)
  currentSkinGenerate: 'LINK'
hook-plugin:
  ## EssentialsX プラグインに対応するか
  hook-essentials-x: true
  ## SuperVanish プラグインに対応するか
  hook-super-vanish: true
  ## VanishNoPacket プラグインに対応するか
  hook-vanish-no-packet: true
  ## 複数のVanishに対応している可能性がある
  legacy-vanish: true
log:
  default-log:
    advanced-settings:
      ## コマンドログのログをテキストチャンネルに送信します
      command-log: false
      ## コンソールのログをテキストチャンネルに送信します
      console-log: false
      ## コンソールとしてコマンドを実行します
      console-command: false
      ## 参加しsたときのログをテキストチャンネルに送信します
      join-log: true
      ## 抜けたときのログをテキストチャンネルに送信します
      left-log: true
      ## チャットのログをテキストチャンネルに送信します
      chat-log: true
      ## ディスコードのメッセージをサーバーに送信します
      chat: true
      ## チャットがプラグインによってキャンセルされた場合に送信しないようにするか
      ignore-cancel-chat: true
    channelId: 'CHANNEL_ID_HERE'
  operator-log:
    advanced-settings:
      ## ONにするもの以外省略可能
      console-log: true
      console-command: true
    channelId: 'CHANNEL_ID_HERE'
messages:
  success-hook: 'プレイヤーロールコネクターの接続に成功しました！'
  cannot-find-hook: 'プレイヤーロールコネクターに接続に失敗しました・・・！'
  ## %name% - 登録成功した名前
  success-register: '%name% の登録に成功しました'
  text-channel-id-zero: 'テキストチャンネルのIDがゼロです！'
  ## %date% - コンソールの日付
  ## %level% - メッセージのレベル
  ## %logger_name% - ロガーの名前 [例: [DiscordChat]]
  ## %msg% - メッセージ
  console-log: '[%date% %level%]: %logger_name% %msg%'
  ## %name% - ディスコードのプレイヤー名 [例: Kouta1212]
  ## %display_name% - ディスコードのディスプレイ名 [例: こうた]
  ## %full_name% - ディスコードのプレイヤー名 [例: Kouta1212#0001]
  ## %top_level_role% - 現在のロールの上位1件を取得します
  ## %color% - ロールのカラーをマインクラフトで再現 (Require Minecraft 1.16+)
  chat-message: '%display_name% > %msg% [%full_name% |%color% %top_level_role%&f]'
  ## 登録されている場合のメッセージ getPlayerData をtrueにする場合に使うことが可能です
  chat-message-registered: '[Verified]%display_name% > %msg% [%full_name% |%color% %top_level_role%&f]'
  ## ロールがない場合に使われる
  non-role: 'N/A'