global-settings:
  console-log: true
hook-plugin:
  hook-essentials-x: true
  hook-super-vanish: true

log:
  default-log:
    advanced-settings:
      command-log: false
      console-log: false
      join-log: true
      left-log: true
      chat-log: true
    channelId: 'CHANNEL_ID_HERE'
  operator-log:
    advanced-settings:
      ## ONにするもの以外省略可能
      console-log: true
    channelId: 'CHANNEL_ID_HERE'
messages:
  success-hook: 'プレイヤーロールコネクターの接続に成功しました！'